In [1]:
c = 1
x = 2
y = 1

simple_prob = lambda t: (c/x*y)**(t+1) # probabilidad de ser golpeado si el objeto solo ocupa un cuadrado (n, m)

In [30]:
import numpy as np

def graph_cases (y, x, c, t):
    counter = 0
    drop_locs = [[z, 0] for z in range(c)] # {x, y} // Iniciamos las posiciones en y=0 y x = [numero de gota]
    
    def draw ():
        t_matrix = np.zeros([y, x])            
        for drop in drop_locs:
            t_matrix[drop[1]%y][drop[0]%x] = 1
        print ("#{} \n{}\n--------\n".format(counter, t_matrix))
    
    g_done = [0 for n in range (c)] # cuando la gota G llega a (x, y) => g_done[G] = 1
    while (True):
        draw();
        for gota in range (c): 
            if (drop_locs[gota][0] == x-1) and (drop_locs[gota][1] == y-1):
                g_done[gota] = 1; drop_locs[gota] = [0, 0];
            elif (drop_locs[gota][0] == x-1): drop_locs[gota][1]+=1; drop_locs[gota][0] = 0;
            else: drop_locs[gota][0] += 1
        counter += 1;
        if (sum(g_done) == c): break;
    print ("=> Hubieron {} casos".format(counter))

graph_cases (2, 2, 2, 1)

#0 
[[1. 1.]
 [0. 0.]]
--------

#1 
[[0. 1.]
 [1. 0.]]
--------

#2 
[[0. 0.]
 [1. 1.]]
--------

#3 
[[1. 0.]
 [0. 1.]]
--------

=> Hubieron 4 casos
